apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.product.company.com
spec:
  group: product.company.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              nginx:
                type: string
          status:
            type: object
            properties:
              message:
                type: string
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example
